### ISSUE TITLE
Use of renamed SchemaCommand

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/psx-schema#12]
SchemaCommand was renamed to ParseCommand in [this](https://github.com/apioo/psx-schema/commit/260f283159d6683cd8489622a1af9556f09a8e00) commit.

But bin/schema still calls SchemaCommand, which causes "Class not found" errors:
* https://github.com/apioo/psx-schema/blob/79cc1a82785846e80747d6f220290d090f58bb5d/bin/schema#L47

**Comment by chriskapp** [comment]
Hi, thanks for the info. I have just fixed the problem (https://github.com/apioo/psx-schema/commit/fc1e080edd232e986bf1a8208f3b60b3728d4b0c) and also added a test case to detect problems with the bin script in the future.
