### ISSUE TITLE
Attempting to Run

### ISSUE THREAD

**Issue by ayenter** [apioo/psx-schema#15]
I did `composer install`, but I do not see a `vendor/bin/schema` to run.

Installation instructions would be helpful.

**Comment by chriskapp** [comment]
Hi, so if you require this package `psx/schema` as dependency in your `composer.json`, composer should automatically create this bin script for you copied from `bin/schema`. Regarding the install instructions, the idea was that it is a library which you include in your project so there is basically no installation required. Or do you want to use it more like a standalone binary, then we could also think about building a standalone `.phar` release.

**Comment by ayenter** [comment]
Ah, that makes sense. It would be helpful to have a standalone binary option.

But the bigger issue I was running into is that the command is different then described in the README.md:
`vendor/bin/schema schema schema.json php`
should be
`vendor/bin/schema schema:parse --format=php schema.json`

**Comment by chriskapp** [comment]
You are right, I have just updated the readme with the correct command.
