### ISSUE TITLE
These exception message should be than not then, a typo? And how can i customize these messages?

### ISSUE THREAD

**Issue by guweigang** [apioo/psx-schema#17]
https://github.com/apioo/psx-schema/blob/533192678b820a8fe5eaed13e4055330a710079e/src/SchemaTraverser.php#L489-L504

**Comment by guweigang** [comment]
thank you very much.

**Comment by chriskapp** [comment]
Hi, yes you are correct it should be `than` in the exception message so its basically a typo. If you like you can submit a PR to fix this otherwise I can also easily fix it.

**Comment by chriskapp** [comment]
so I have just fixed the typos, this will be included in the next release
