### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by XanderEmu** [apioo/psx-schema#2]
Hello,

How come this lib has so many dependencies?
For example what does it need doctrine/dbal for?

**Comment by chriskapp** [comment]
Hi, we try to have as less dependencies as possible. The `doctrine/dbal` comes through the `psx/validate` package. It depends on it because it has a filter which works with a database and type hints the `Connection`. Probably we should move this filter somewhere else to remove this dependency.

**Comment by chriskapp** [comment]
So I have just released a new verison of the `psx/validate` package which therefore removes the `doctrine/dbal` dependency from this library.
