### ISSUE TITLE
Configure POPOs without annotations?

### ISSUE THREAD

**Issue by XanderEmu** [apioo/psx-schema#3]
Is that possible to configure POPOs without annotations? YAML? XML? Plain PHP? Anything?

**Comment by chriskapp** [comment]
Hi, so besides annotations you can use either a json schema file or create a class which extends the [SchemaAbstract] class and use the builder to configure the schema. You can then use the loader `$schemaManager->getSchema("schema.json");` or `$schemaManager->getSchema(MySchema::class);` to
obtain the POPO.

[SchemaAbstract]: https://github.com/apioo/fusio-impl/blob/master/src/Backend/Schema/Routes.php#L35
