### ISSUE TITLE
[Semantical Error] Annotation @Items is not allowed to be declared on property

### ISSUE THREAD

**Issue by bstoots** [apioo/psx-schema#5]
I am having issues using the `@Items` annotation as of release v2.1.1, specifically:

> [Semantical Error] Annotation `@Items` is not allowed to be declared on property Data::$items.  You may only use this annotation on these code elements: CLASS.

According to README.md the `@Items` annotation should target PROPERTY.  I double checked the source and it appears this is incorrectly targeting CLASS instead.  Simply changing `@Target("CLASS")` to `@Target("PROPERTY")` in PSX\Schema\Parser\Popo\Annotation\Items.php makes everything work properly for me.

If I'm missing something please let me know, otherwise I would be happy to create a PR for this fix.

Thanks

**Comment by chriskapp** [comment]
Hi, yes you are right this a bug it should be `PROPERTY` instead of `CLASS`. You are welcome to make a pull request.

It is interesting that this error does not came up through the tests since we have an annotation test:
https://github.com/apioo/psx-schema/blob/master/tests/Parser/Popo/News.php#L204

which checks whether the parsing of the annotations works. In the test case the library can read the `@Items` annotations even if it has the wrong target. Iam currently not sure why this is the case but I will try to find the reason.

**Comment by bstoots** [comment]
I suspect the issue here is the use of `SimpleAnnotationReader`.  From a cursory glance it does not appear that this implementation of the `Doctrine\Common\Annotations\Reader` interface ever sets the target annotation type.

For example if you dig into `Doctrine\Common\Annotations\DocParser` you'll find a line like this:

```
$target = $this->isNestedAnnotation ? Target::TARGET_ANNOTATION : $this->target;
```

When `Doctrine\Common\Annotations\SimpleAnnotationReader` is used `$this->target` is always null which then causes this check to always return false:

```
if (0 === (self::$annotationMetadata[$name]['targets'] & $target) && $target) {
```

This would explain why the tests are passing, the use of `SimpleAnnotationReader` is essentially treating all `@Target` annotations as `@Target("ALL")`.

**Comment by chriskapp** [comment]
That makes sense. I think I will try to change the `Reader` implementation in the test case to the `AnnotationReader` so that we also find such configuration errors.

**Comment by chriskapp** [comment]
I just changed the test cases 8d3321d536e5a6bd62290f7a541abbf3cca33cba to use the `AnnotationReader` instead of the `SimpleAnnotationReader` this should help to find annotation configuration errors in the future.

**Comment by bstoots** [comment]
Great, thanks a lot.  Any idea when you plan on cutting a new release version?

**Comment by chriskapp** [comment]
No problem, I have just released a new version. If you have any issues or feature requests please let me know.
