### ISSUE TITLE
Online tool is offline (404 error)

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/psx-schema#9]
The [online tool](http://phpsx.org/schema/generator) (linked inside README) is currently offline:
![online_tool](https://user-images.githubusercontent.com/28066477/30523685-fc5e18d6-9be5-11e7-83e5-f7946517fd9c.png)

**Comment by chriskapp** [comment]
Hi, sorry the link has changed it is available at: http://phpsx.org/tools/jsonschema but I will update the link from the readme now.

**Comment by chriskapp** [comment]
The url is fixed in the readme thus I will close the issue
